services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole.bi-frost
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80
    environment:
      TZ: 'Europe/London'
    volumes:
      - dnsmasqd:/etc/dnsmasq.d
      - data:/etc/pihole

volumes:
  data:
  dnsmasqd:
